---
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: ./app
    id: kuma-counter-demo
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - README.md
      - k8s

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - id: demo-app-amd64
    use: buildx
    goarch: amd64
    image_templates:
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Tag }}-amd64
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Major }}-amd64
      - ghcr.io/kumahq/kuma-counter-demo:latest-amd64
    dockerfile: ./app/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.source=https://github.com/kumahq/kuma-counter-demo"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - id: demo-app-arm64
    use: buildx
    goarch: arm64
    image_templates:
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Tag }}-arm64
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Major }}-arm64
      - ghcr.io/kumahq/kuma-counter-demo:latest-arm64
    dockerfile: ./app/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.source=https://github.com/kumahq/kuma-counter-demo"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

  - id: demo-app-debian-slim-amd64
    use: buildx
    goarch: amd64
    image_templates:
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Tag }}-debian-slim-amd64
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Major }}-debian-slim-amd64
      - ghcr.io/kumahq/kuma-counter-demo:debian-slim-amd64
    dockerfile: ./app/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.source=https://github.com/kumahq/kuma-counter-demo"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=BASE_IMAGE=debian:12.8-slim"
      - "--platform=linux/amd64"
  - id: demo-app-debian-slim-arm64
    use: buildx
    goarch: arm64
    image_templates:
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Tag }}-debian-slim-arm64
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Major }}-debian-slim-arm64
      - ghcr.io/kumahq/kuma-counter-demo:debian-slim-arm64
    dockerfile: ./app/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.source=https://github.com/kumahq/kuma-counter-demo"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--build-arg=BASE_IMAGE=debian:12.8-slim"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/kumahq/kuma-counter-demo:{{ .Tag }}"
    image_templates:
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Tag }}-amd64
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Tag }}-arm64
  - name_template: "ghcr.io/kumahq/kuma-counter-demo:{{ .Major }}"
    image_templates:
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Major }}-amd64
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Major }}-arm64
  - name_template: "ghcr.io/kumahq/kuma-counter-demo:latest"
    image_templates:
      - ghcr.io/kumahq/kuma-counter-demo:latest-amd64
      - ghcr.io/kumahq/kuma-counter-demo:latest-arm64
  - name_template: "ghcr.io/kumahq/kuma-counter-demo:{{ .Tag }}-debian-slim"
    image_templates:
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Tag }}-debian-slim-amd64
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Tag }}-debian-slim-arm64
  - name_template: "ghcr.io/kumahq/kuma-counter-demo:{{ .Major }}-debian-slim"
    image_templates:
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Major }}-debian-slim-amd64
      - ghcr.io/kumahq/kuma-counter-demo:{{ .Major }}-debian-slim-arm64
  - name_template: "ghcr.io/kumahq/kuma-counter-demo:debian-slim"
    image_templates:
      - ghcr.io/kumahq/kuma-counter-demo:debian-slim-amd64
      - ghcr.io/kumahq/kuma-counter-demo:debian-slim-arm64

release:
  draft: true
