[settings]
experimental = true # To enable installation of Go tools from source with mise.

[tools]
golangci-lint = '2.12.2'
goreleaser = '2.16.0'
oapi-codegen = '2.7.1'
skaffold = '2.23.0'
kustomize = '5.8.1'
