// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
)

// Counter defines model for Counter.
type Counter struct {
	// Counter The incremented counter value
	Counter int `json:"counter"`

	// Zone Zone data from Redis
	Zone string `json:"zone"`
}

// DeleteCounterResponse defines model for DeleteCounterResponse.
type DeleteCounterResponse = Counter

// Error standard error
type Error struct {
	// Detail Details about the error.
	Detail *string `json:"detail,omitempty"`

	// Instance The portal traceback code
	Instance string `json:"instance"`

	// InvalidParameters TODO
	InvalidParameters *[]InvalidParameters `json:"invalid_parameters,omitempty"`

	// Status The HTTP status code.
	Status int `json:"status"`

	// Title The error response code.
	Title string `json:"title"`

	// Type The error type.
	Type *string `json:"type,omitempty"`
}

// GetCounterResponse defines model for GetCounterResponse.
type GetCounterResponse = Counter

// InvalidParameters defines model for InvalidParameters.
type InvalidParameters struct {
	Choices *[]string `json:"choices,omitempty"`
	Field   *string   `json:"field,omitempty"`
	Reason  *string   `json:"reason,omitempty"`
	Rule    *string   `json:"rule,omitempty"`
}

// KV defines model for KV.
type KV struct {
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	UpdatedBy *string    `json:"updatedBy,omitempty"`
	Value     string     `json:"value"`
}

// KVDeleteResponse defines model for KVDeleteResponse.
type KVDeleteResponse = KV

// KVGetResponse defines model for KVGetResponse.
type KVGetResponse = KV

// KVListResponse defines model for KVListResponse.
type KVListResponse struct {
	Keys []string `json:"keys"`
}

// KVPostRequest defines model for KVPostRequest.
type KVPostRequest struct {
	Expect *string `json:"expect,omitempty"`
	Value  string  `json:"value"`
}

// KVPostResponse defines model for KVPostResponse.
type KVPostResponse = KV

// PostCounterResponse defines model for PostCounterResponse.
type PostCounterResponse = Counter

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// Color Application color in HEX format
	Color string `json:"color"`

	// Version Application version
	Version string `json:"version"`
}

// KvPostJSONRequestBody defines body for KvPost for application/json ContentType.
type KvPostJSONRequestBody = KVPostRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Reset the counter
	// (DELETE /counter)
	DeleteCounter(w http.ResponseWriter, r *http.Request)
	// Get the current counter value
	// (GET /counter)
	GetCounter(w http.ResponseWriter, r *http.Request)
	// Increment the counter
	// (POST /counter)
	PostCounter(w http.ResponseWriter, r *http.Request)
	// Returns all values currently available
	// (GET /key-value)
	KvList(w http.ResponseWriter, r *http.Request)
	// delete a value in a kv
	// (DELETE /key-value/{key})
	KvDelete(w http.ResponseWriter, r *http.Request, key string)
	// Returns the value for a key or 404 if not found
	// (GET /key-value/{key})
	KvGet(w http.ResponseWriter, r *http.Request, key string)
	// Set a value of a kv
	// (POST /key-value/{key})
	KvPost(w http.ResponseWriter, r *http.Request, key string)
	// Get the application version and color
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteCounter operation middleware
func (siw *ServerInterfaceWrapper) DeleteCounter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCounter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCounter operation middleware
func (siw *ServerInterfaceWrapper) GetCounter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCounter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCounter operation middleware
func (siw *ServerInterfaceWrapper) PostCounter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCounter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KvList operation middleware
func (siw *ServerInterfaceWrapper) KvList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KvList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KvDelete operation middleware
func (siw *ServerInterfaceWrapper) KvDelete(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", mux.Vars(r)["key"], &key, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KvDelete(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KvGet operation middleware
func (siw *ServerInterfaceWrapper) KvGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", mux.Vars(r)["key"], &key, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KvGet(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KvPost operation middleware
func (siw *ServerInterfaceWrapper) KvPost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", mux.Vars(r)["key"], &key, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KvPost(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/counter", wrapper.DeleteCounter).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/counter", wrapper.GetCounter).Methods("GET")

	r.HandleFunc(options.BaseURL+"/counter", wrapper.PostCounter).Methods("POST")

	r.HandleFunc(options.BaseURL+"/key-value", wrapper.KvList).Methods("GET")

	r.HandleFunc(options.BaseURL+"/key-value/{key}", wrapper.KvDelete).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/key-value/{key}", wrapper.KvGet).Methods("GET")

	r.HandleFunc(options.BaseURL+"/key-value/{key}", wrapper.KvPost).Methods("POST")

	r.HandleFunc(options.BaseURL+"/version", wrapper.GetVersion).Methods("GET")

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYbW/bOBL+KwTvgPsiW46TXAt9S18uDVpcg7QoFlsEi4k0tllLpJYcuXEL//cFSVmS",
	"JcZNgBpwgX6TxCE58zzzqu88VUWpJEoyPPnOTbrAAtzjS1VJQm0fS61K1CTQLaTtQoYm1aIkoSRP+McF",
	"MiFTjQVKwozVgmwFeYU84rQukSdcSMI5ar6J+DclcXjOn0oiy4CAzbQq2A1mwrTbDWkh53yzibjGvyuh",
	"MePJ50ar+tDbRl7dfcGUeMTvR3gPRZl7K17755Mdi6anW514ZUZf0RDf2IteYY6ENSI3aEolDf5GZhPx",
	"11qrgMGGQGagM4ZuPeoBlSGByIfbXrnvhsGdqojRAv3+MY94rWENprUPjYWSEAr2FQyTithMVTIbAhJx",
	"Ia1GKYapKZUmyBlpSPEO0iVLVYY7d3qJxEkk0+nzZ9Pn59PJs/+enp9MTycnJ+E7V5CL7K8SNBRIqE3g",
	"9vev3vOIC8LCrf5b44wn/F9xG5ZxHZPxlT/vuj1u09wKWsPavhsCqkzYzDcfP14zL+As3IH1bHIW8kMS",
	"lD+AmqOG6Toahify/yti/3uIEf/h4XPt+qOP63l8DcJW+w79t41Ftec+MhjYSddtey6YqbSygT1ww9br",
	"HuNAW+o8E7WWAaMXRKVJ4nip5BxKMRZypuJlVcCojtZRhoWKpaKRV8QF6iXS7/w1zF/DoBqislAi9Y9N",
	"nD7gzm0czgTmWVBSIxgLRmip8rE2xGPrDrW6rKNvH45NxN9+GlpRlRkQZhdkX2ZKF0A84fbbiESBoRCt",
	"t7xYB5X13Ae17bLnxW6DWvqy+rA/HqPOl0i/lsLvhNmj8RLXT/Ls3sVue/jea2XvdTlyeC3el1bwQCb7",
	"q38dkqy+v5PzMDl/Qm2EkvswyUPd50VZ5iIF+8acCBOSvXn9B6vZDjC88lftP2sr9CNQWjmv4JBz26lh",
	"WmlB6w+2vfPmvEDQqC8qWjSzmN105z7vNgAeIFv6Qw4hDLu4vmKlViuRoWEWM2eCsRCwAiTMhZwzaJwF",
	"ZMY0kha4sgvftr4w5m3xedmRdc5ycX3FO9Dxk/FkPLFoqhIllIIn/HQ8GZ/a/h9o4WyMd/zY5v/QGGC/",
	"GzcAbBVsfbKrK5pdVRtDr7LmnJeNi257VafIdDLxLiQJpcsF0FIdf6lrtG++f9Sah+dDR9GuZR+qNEVj",
	"ZlVuG2ckpmZdKy125z9RL9/jBvS4YHeQsRmIvNLo3bEqCtBrnvAbp1hPqznSkKebhgQnXWltu2CXd3qG",
	"Oc72MNV2p4ekKdAD/4gjZyDkfXN8bj0Gti63XNXoDzQslQlQd7UtGJ47H1iBZFBzu4e6TvE6JHehGrmf",
	"vKYmHmOQNfjvaraJeLzE9ahpKYJxZyt+LowzbIlrx5fbYckCYngvDA2Iert65z8fjKNes/mE2LLWHEny",
	"o0pLwyDPt5DWkZWvGaxA5HCXY4+o+PsS15vditbH3peIw6Lfm6f24+9VjSwPzmLrh6XGlVCVabPH2eTs",
	"8ISkIP9DbF5nsvruHVq8sgzq4iIkA7ZcdQpTH+5LPLCnd+fAJzj6EtdHBOtNh3uPrG0PwSUVpdnZ5IyJ",
	"WeeXli0nnT8ln0OJSULRVH9rbfcXXjstCCtum0IecbuDJ9wLt3006QqjDgb9nvu2rW199m2xqM9CQy9U",
	"tv6JzHcH2wDq1xVt/w0OzNkc1CV3xt79PumAOx4//IDUxLaa1bFtU2xnLHtEBwrDWc3VRj8DGiQScm6C",
	"3eenZmQ7GEH9afYJWWNojJ387Cxr9x1TG7qXAn+oQb0Kp493KgVbmFaYq9I1R16WR7zSeT35JnGcW7mF",
	"MpScT84nsZ00N7ebfwIAAP//7WqdyswcAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
