// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
)

// Counter defines model for Counter.
type Counter struct {
	// Counter The incremented counter value
	Counter int `json:"counter"`

	// Zone Zone data from Redis
	Zone string `json:"zone"`
}

// DeleteCounterResponse defines model for DeleteCounterResponse.
type DeleteCounterResponse = Counter

// Error standard error
type Error struct {
	// Detail Details about the error.
	Detail *string `json:"detail,omitempty"`

	// Instance The portal traceback code
	Instance string `json:"instance"`

	// InvalidParameters TODO
	InvalidParameters *[]InvalidParameters `json:"invalid_parameters,omitempty"`

	// Status The HTTP status code.
	Status int `json:"status"`

	// Title The error response code.
	Title string `json:"title"`

	// Type The error type.
	Type *string `json:"type,omitempty"`
}

// GetCounterResponse defines model for GetCounterResponse.
type GetCounterResponse = Counter

// InvalidParameters defines model for InvalidParameters.
type InvalidParameters struct {
	Choices *[]string `json:"choices,omitempty"`
	Field   *string   `json:"field,omitempty"`
	Reason  *string   `json:"reason,omitempty"`
	Rule    *string   `json:"rule,omitempty"`
}

// KV defines model for KV.
type KV struct {
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	UpdatedBy *string    `json:"updatedBy,omitempty"`
	Value     string     `json:"value"`
}

// KVDeleteResponse defines model for KVDeleteResponse.
type KVDeleteResponse = KV

// KVGetResponse defines model for KVGetResponse.
type KVGetResponse = KV

// KVListResponse defines model for KVListResponse.
type KVListResponse struct {
	Keys []string `json:"keys"`
}

// KVPostRequest defines model for KVPostRequest.
type KVPostRequest struct {
	Expect *string `json:"expect,omitempty"`
	Value  string  `json:"value"`
}

// KVPostResponse defines model for KVPostResponse.
type KVPostResponse = KV

// PostCounterResponse defines model for PostCounterResponse.
type PostCounterResponse = Counter

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// Version Application version
	Version string `json:"version"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// KvPostJSONRequestBody defines body for KvPost for application/json ContentType.
type KvPostJSONRequestBody = KVPostRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Reset the counter
	// (DELETE /counter)
	DeleteCounter(w http.ResponseWriter, r *http.Request)
	// Get the current counter value
	// (GET /counter)
	GetCounter(w http.ResponseWriter, r *http.Request)
	// Increment the counter
	// (POST /counter)
	PostCounter(w http.ResponseWriter, r *http.Request)
	// Returns all values currently available
	// (GET /key-value)
	KvList(w http.ResponseWriter, r *http.Request)
	// delete a value in a kv
	// (DELETE /key-value/{key})
	KvDelete(w http.ResponseWriter, r *http.Request, key string)
	// Returns the value for a key or 404 if not found
	// (GET /key-value/{key})
	KvGet(w http.ResponseWriter, r *http.Request, key string)
	// Set a value of a kv
	// (POST /key-value/{key})
	KvPost(w http.ResponseWriter, r *http.Request, key string)
	// Get the application version and color
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteCounter operation middleware
func (siw *ServerInterfaceWrapper) DeleteCounter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCounter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCounter operation middleware
func (siw *ServerInterfaceWrapper) GetCounter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCounter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCounter operation middleware
func (siw *ServerInterfaceWrapper) PostCounter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCounter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KvList operation middleware
func (siw *ServerInterfaceWrapper) KvList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KvList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KvDelete operation middleware
func (siw *ServerInterfaceWrapper) KvDelete(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", mux.Vars(r)["key"], &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KvDelete(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KvGet operation middleware
func (siw *ServerInterfaceWrapper) KvGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", mux.Vars(r)["key"], &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KvGet(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KvPost operation middleware
func (siw *ServerInterfaceWrapper) KvPost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", mux.Vars(r)["key"], &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KvPost(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/counter", wrapper.DeleteCounter).Methods(http.MethodDelete)

	r.HandleFunc(options.BaseURL+"/counter", wrapper.GetCounter).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/counter", wrapper.PostCounter).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/key-value", wrapper.KvList).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/key-value/{key}", wrapper.KvDelete).Methods(http.MethodDelete)

	r.HandleFunc(options.BaseURL+"/key-value/{key}", wrapper.KvGet).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/key-value/{key}", wrapper.KvPost).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/version", wrapper.GetVersion).Methods(http.MethodGet)

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fjdbts4E30Vgt8H7I1sOU6yLXSX/mw2aLEN0qIXWwSLiTS2WUuklhy5cQu/+4KkLMkS4yZADbhA72xp",
	"SJ45Z/6obzxVRakkSjI8+cZNusAC3M+XqpKE2v4stSpRk0D3Im1fZGhSLUoSSvKEf1ggEzLVWKAkzFht",
	"yFaQV8gjTusSecKFJJyj5puIf1USh/v8rSSyDAjYTKuC3WAmTLvckBZyzjebiGv8txIaM558alDVm942",
	"9uruM6bEI34/wnsoytx78dr/PtnxaHq6xcQrM/qChvjGHvQKcySsGblBUypp8Bczm4i/1loFHDYEMgOd",
	"MXTvox5RGRKIfLjslXtuGNypihgt0K8f84jXCGsyrX9oLJWEULAvYJhUxGaqktmQkIgLaRGlGJamVJog",
	"Z6QhxTtIlyxVGe6c6S0SZ5FMp8+fTZ+fTyfPfj89P5meTk5OwmeuIBfZPyVoKJBQm8Dp71694xEXhIV7",
	"+3+NM57w/8VtWsZ1TsZXfr/rdrtNcypoDWv73xBQZcJu/vnhwzXzBs7DHVrPJmehOCRB+QOsOWmYrrNh",
	"uCP/SxH74yFF/IOH97XvH71dL+JrErboO/LfNh7VkfvIZGAn3bDthWCm0som9iAM26h7TABtpfNK1CgD",
	"Ti+ISpPE8VLJOZRiLORMxcuqgFGdraMMCxVLRSMPxCXqJdKv+jWsX8OkGrKyUCL1P5s8fSCc2zycCcyz",
	"oKVGMJaM0KvK59qQj2041HBZB2+fjk3E33wcelGVGRBmF2T/zJQugHjC7bMRiQJDKVovebEOgvXaB9F2",
	"1fNmt0GUvq0+HI/HiPkS6ecC/FaYPYiXuH5SZPcOdsvD514re66rkcNj8b60hgdy2R/984hk8f4qzsPi",
	"/BG1EUo+zMnKGwx9uSjLXKRg/7Gt0fdcae1SlSsdUMrOV5hWWtD6vR3KPIgXCBr1RUWL5gZlF925x7tt",
	"27tlG3ZIRmHYxfUVK7VaiQwNs546FwybKc0KkDAXcs6gkRhkxjSSFriyL75uFRzztmW87Ng6iS+ur3jU",
	"UsdPxpPxxIaFKlFCKXjCT8eT8amd2oEWzsd4J/ps1Q4N7/a5cWP7FmAbSV2saHahNo5eZc0+L5vA2k6Y",
	"Dsh0MvGhIwmly2BopY4/153Vj8zfG6jDtzon0a5n76s0RWNmVW7HXSSmZl0vLXfnPxCXn0wDOC7YHWRs",
	"BiKvNPpwrIoC9Jon/MYB66GaIw11umlEcNaV1nZ2ddWi55jTbI9S7Ux5SJkCk+v3NHIOQt53x1fEY1Dr",
	"cqtVzf4AYalMQLqrbZn32vnEChSDWts90nVaziG1C3W2/eI1newYk6zhfxfZJuLxEtejZhAI5p3t07kw",
	"zrElrp1eboUVC4jhvTA0EOrN6q1/fDCNeiPiE3LLenMkxY8qLQ2DPN9SWmdWvmawApHDXY49oeJvS1xv",
	"djtan3vfIg7Lfu8WtJ9/DzWyOjiPbRyWGldCVaatHmeTs8MLkoL8jdi8rmT12TuyeLAM6uYiJAO2XHUa",
	"U5/uSzxwpHdvb08I9CWuj4jWm472nlk7HoIrKkqzs8kZE7POhyjbTjrfNz6FCpOEoun+1tvuh7d2xhfW",
	"3A6FPOJ2BU+4N27naNIVRh0O+jP3bdvb+urbZlHvhYZeqGz9A5XvXkcDrF9XtP2iN3Bnc9CQ3Lms7o9J",
	"R9zxxOF7pCa31azObVtiO9eyR0ygMLyrud7obmHMIJGQcxOcPj82V7aDCdS/gz6hagydsTc/XTgYRzWG",
	"7pXAb2pQr8Ll461KwTamFeaqdMORt+URr3Re33yTOM6t3UIZSs4n55PY3jQ3t5v/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
