apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  namespace: kuma-demo
  name: kv
spec:
  targetRef:
    kind: MeshSubset
    tags:
      app: kv
  from:
    - targetRef:
        kind: MeshSubset
        tags:
          app: demo-app
          k8s.kuma.io/namespace: kuma-demo
      default:
        action: Allow
