name: project-lifecycle
on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:
  issues:
    types:
      - reopened
      - opened
      - labeled

jobs:
  lifecycle:
    uses: kumahq/.github/.github/workflows/wfc_lifecycle.yml@9e5f50367a10d2a24ec254bdeac03b5f40bde55c
